controllers:
    resource: ../src/Controller/
    type: attribute
main:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_main'
        permanent: true